---
title: "EWS Aufgabe 9.3"
author: "April Herwig"
date: "1/19/2021"
header-includes:
   - \usepackage{amsmath}
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

#### *a)* 

$$\begin{equation*}
E[T_1] = E[\frac{1}{n} \sum\limits_{i=1}^{n} X_i] = \frac{1}{n}\sum\limits_{i=1}^n E[X_i] = \frac{1}{n} n \theta
\end{equation*}
$$

$$\begin{equation*}
E[T_2] = E[\frac{1}{n+2} \left( \sum\limits_{i=1}^{n}X_i + 1 \right) ] = \frac{1}{n+2} n E[X_i] + \frac{1}{n+2} = \frac{1}{n+2}(n\theta + 1)
\end{equation*}$$




#### *b)*

$$\begin{equation*}
    \begin{split}
        E[T_1^2] & = Var(T_1) + E[T_1]^2 = \frac{1}{n^2} \sum\limits_{i=1}^{n} Var(X_i) + \theta ^2 \\ 
        & = \frac{n}{n^2} Var(X_i) + \theta ^2 = \theta(1-\theta) + \theta ^2 = \theta \\
        \\
        \Rightarrow MSI_{\theta}(T_1) & = E[T_1^2 - 2 \theta T_1 + \theta] \\
        & = E[T_1^2] - 2 \theta E[T_1] + \theta^2 \\
        & = \theta - \theta^2
    \end{split}
\end{equation*}$$

\ 

$$\begin{equation*}
    \begin{split}
        E[T_2^2] & = Var(T_2) + E[T_2]^2 \\
        & = \left(\frac{1}{n+2}\right)^2\; \sum\limits_{i=1}^{n} Var(X_i) + E[T_2]^2 \quad\leftarrow \quad * \\
        & = \frac{n}{(n+2)^2} (\theta(1-\theta)) + \left(\frac{n\theta +1}{n+2}\right)^2 \\
        & = \frac{1 + 3n\theta}{(n+2)^2} \\
        \\
        \Rightarrow\; MSI_{\theta}(T_2) & = E[T_2^2 -2\theta T_2  + \theta ^2] = \frac{1 + 3n\theta}{(n+2)^2} - 2\theta\frac{n\theta +1}{n+2} + \theta ^2\\
    \end{split}
\end{equation*}$$

\* Var ist Translationsinvariant und $X_i$ sind unabhängig per Annahme.

#### *c)*

```{r}
MSE_T1 <- function(n, theta) {
  return(theta - theta^2)
}

MSE_T2 <- function(n, theta) {
  e1 <- (1+3*n*theta)/((n+2)^2)
  e2 <- (n*theta+1)/(n+2)
  return(e1-2*theta*e2+(theta^2))
}
```

```{r}
MSE1 <- tibble(
  theta = rep(c(1:100)*0.01, 3),
  n = c(rep("10", 100),
        rep("60", 100),
        rep("100", 100)
        )
)

MSE1 <- MSE1 %>%
  mutate(MSE = MSE_T1(as.numeric(n), theta))

MSE2 <- tibble(
  theta = rep(c(1:100)*0.01, 3),
  n = c(rep("10", 100),
        rep("60", 100),
        rep("100", 100)
        )
)

MSE2 <- MSE2 %>%
  mutate(MSE = MSE_T2(as.numeric(n), theta))
MSE2
```

```{r}
ggplot(data=MSE1, mapping=aes(x=theta, y=MSE, color=n)) + 
  geom_line()
```

```{r}
ggplot(data=MSE2, mapping=aes(x=theta, y=MSE, color=n)) + 
  geom_line()
```

